### PR TITLE
Added Linear Motion

### PR DESCRIPTION
**Pull request by Kuppharish**
I've created new environment which doesn't have the ball joint and is free to move. I've also made changes so that this environment returns the three linear velocities, three angular velocities and four rotor rpms. The new models name is **AttFC_GyroErr-MotorVel_M4_E-v1**  

Please review the pull request and tell me if any changes are needed to be done.

### CODE REVIEW

**Comment by wil3** [comment]
Hi @Kuppharish thanks for the contribution. I quickly looked at the changes however you haven't included the position as part of the target, reward or state. As of now for an RL task adding the velocity doesn't do anything.

Edit: Couple more things that need to eventually be addressed. Please create more meaningful environment names rather than just appending a "1". Additionally please include some sort of test script (e.g. using PID) to ensure the environment is operating correctly (e.g. https://github.com/wil3/gymfc/tree/master/gymfc/controllers).

**Comment by Kuppharish** [comment]
What do you mean by adding position as a target? 
I'll change the environment names appropriately. 
I'm thinking of using PID for the drone to maintain certain constant linear velocities. What do you think of that?

**Comment by wil3** [comment]
Are you familiar with [OpenAI Gym](https://github.com/openai/gym)? GymFC is an OpenAI gym environment so its primary purpose is to train intelligent (i.e. neural network) systems flight control, although it can be used for other simulations (i.e. PID). Because it is a Gym environment all environments must reflect this. If this is new I suggest reading up on OpenAI gyms and looking at some of their example environments.

What I mean by adding position as the target is that in an environment you must have a goal you are attempting to achieve (the target). The previous environments goals are to achieve the desired angular velocity (attitude) so you must first define this goal in sample_target (or equivalent function) https://github.com/wil3/gymfc/blob/master/gymfc/envs/attitude_control_env.py#L13. In the linked function we are sampling a random angular velocity the controller must reach. If you are making an environment based on navigation then the target or goal must reflect this whether that is a trajectory that must be followed or a position it must reached, it all depends on how complicated and how many sensors you want to use. For example if you assume a GPS sensor is onboard then the sampled target may be a sequence of waypoints that must be reached. Or something more complicated may involve LIDAR and obstacles are involved. Hope that helps clarify things.

**Comment by wil3** [comment]
Hi @Kuppharish I appreciate your contribution and commitment to adding this functionality however given its current state I am going to close the pull request since the functionality is not there. Please continue to work on your branch and when you have a working example we can go back to discussing a merge.

**Pull request closed without merging**
