### PR TITLE
Dependency script

### LINKED ISSUE #39: build_plugin script fails with Boost error
I am attempting build the plugin using the build_plugin.sh script. I get a Boost error:
```
/usr/include/boost/math/constants/constants.hpp:343:3: note: use -std=gnu++11 or -fext-numeric-literals to enable more built-in suffixes
/usr/include/boost/math/constants/constants.hpp: In static member function 'static constexpr T boost::math::constants::detail::constant_root_two_div_pi<T>::get(const mpl_::int_<5>&)':
/usr/include/boost/math/constants/constants.hpp:344:3: error: unable to find numeric literal operator 'operator""Q'
```

I tried both of the suggested flags `-std=gnu++11` and `fext-numeric-literals`. Neither of the flags change the error received. I also tried `-DBOOST_MATH_DISABLE_FLOAT128` based on similar issues for other packages, but received the error:
```
c++: fatal error: no input files
compilation terminated.
/bin/sh: 1: -std=c++11: not found
```

I was able to follow all of the other steps in the installation process without any problems, including building DART v6,7 and Gazebo 10 from source.

Some parameters:
Running in Docker container
Ubuntu 16.04
Boost version 1.58
g++/gcc version 6.50

### LINKED ISSUE #58: Add dependency installer script
Make it easier to install the dependencies using a bash script derived from the travis docker file.

### PR DESCRIPTION
**Pull request by wil3**
Closes: #58 
This PR makes installing the dependencies alot easier by just having to run a bash script. 

Turns out installing `pip3 install .` vs in edit mode `pip3 install -e .` is quite different. The custom Gazebo messages can't be found unless LD_LIBRARY_PATH is modified and also gymfc.ini was missing. The included fixes allow for installing via `pip3 install .`.

### CODE REVIEW

**Comment by wil3** [comment]
@xabierolaz @SwapnilPande @varunag18 This PR hopefully will make it a lot easy to install and run GymFC. If you can take a look or even test out the new script since you all have recently be getting the environment setup it would be much appreciated. I tested it in a VirtualBox VM with Ubuntu 18.04 with 15GB harddrive, 2 CPUs and 4GB memory.

**Comment by xabierolaz** [comment]
Great, thanks @wil3 , I'm testing it today, will let you know!

**Comment by varunag18** [comment]
Hi Wil, Im sory but I dont have another machine apart from the one im currently working on, to test the dependency script, but I wil test it once I get a machine at my university. Just having a look at it.....it seems good to go. However, there are certain things I would like to point out that I feel should be more clear for a new user. In the ReadMe file of the i58-dep-script, when we ask the user to 
`sudo MAKE_FLAGS=-j4 ./install_dependencies.sh`
`pip3 install .`
We should explicitly specify the `git clone` command before this.
Also, under the Verify Install heading, when we state the plugin errors, we should add the expected Gazebo style directory structure there itself as well as the method of adding the `.so` files, just like you mentioned [here](https://github.com/wil3/gymfc/issues/40#issuecomment-613155012).

**Comment by SwapnilPande** [comment]
This script looks great and definitely simplifies installing dependencies. It ALMOST worked for me, but still had a few issues.

Since you tried in a VM, I attempted installing in a clean ubuntu 18.04 docker container. The only problem that arose was that the gazebo install directory is set to `/home/$USERNAME/local`. In docker, you are always logged in as root. Therefore, gazebo was incorrectly installed to `/home/local/share/gazebo-10`, when I believe the desired behavior was installing to `/root/local/share/gazebo-10`.

I have a couple of ideas for this:
1. Replace `/home/$USERNAME/local` with with `~/local` for the gazebo install directory.
2. Use the regular install directory for gazebo, `/usr/local`. Out of curiosity, is there a reason you chose to install it in the user's home directory?

**Comment by wil3** [comment]
@SwapnilPande Gazebo recommends installing to /home/$USER/local so you can easily switch between the debian build and the build from source. 

Thanks for trying it in Docker, I'd eventually like to use the same script for the Travis docker so it would be good to have it work for both environments. I'll test it in the VM with the default location (and update gymfc.ini) and if it works as expected could you test it again in Docker?

**Comment by xabierolaz** [comment]
Hi @wil3, can confirm gymfc works greatly on a clean ubuntu 18.04 computer

**Comment by varunag18** [comment]
Thats gr8 @xabierolaz . I need to test this now, as Wil has suggested a problem with my existing installation. Could you provide your thoughts on [the question part](https://github.com/wil3/gymfc/issues/61#issuecomment-633213434) of this comment?

**Comment by varunag18** [comment]
Hi Wil, I did a fresh install using the dependency script and it worked like a breeze. My test scripts are running as expected. Thanks a lot.

**Comment by wil3** [comment]
I made a number of improvements, updated documentation for /examples and fixed the sample_noise bug. 

@SwapnilPande I made the switch to install to /usr/local, tested it in Virtualbox could you give it a try in docker?

**Comment by wil3** [comment]
@all-contributors add @SwapnilPande  for ideas and test

**Comment by wil3** [comment]
@all-contributors add xabierolaz for test

**Comment by wil3** [comment]
@all-contributors add varunag18 for test

**Comment by SwapnilPande** [comment]
Sorry for the slow response, I will test on docker first thing tomorrow morning!

**Comment by SwapnilPande** [comment]
Installation went properly except for adding `usr/local/lib` to the load path. In your install dependencies script you have:
```
echo '/usr/local/lib' | sudo tee /etc/ld.so.conf.d/gazebo.conf
sudo ldconfig
```
When running the script in docker (as root), I get the following error:
```
./install_dependencies.sh: line 74: sudo: command not found
./install_dependencies.sh: line 75: sudo: command not found
```
After manually running these commands without sudo, the gymfc tests work perfectly. 

Since you suggest in your docs running the install_dependencies.sh script with sudo,, you should be able to remove it from the individual commands within the script, correct? With that small change, the script works great!

**Comment by wil3** [comment]
@SwapnilPande awesome thanks for testing that, great catch. Yes I can just remove sudo there. Will make the change then merge this all in. Thanks everyone for the help.

**Comment by wil3** [comment]
Closes: #39

**Pull request merged**
